name: Run ERT tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Emacs
      run: sudo apt install emacs

    - name: Run tests
      run: make test
